site_name: Django Easy Email
site_description: A Django extension designed to streamline email management with powerful templates, scheduling, storage, and more.
site_author: Farhad Hossain
copyright: © 2025, Farhad Hossain
extra:
  version: 1.0.1

repo_url: https://github.com/farhad0085/django-easy-email.git

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Settings: settings.md
  - API Reference:
      - API Reference: api_reference.md
      - Exception: api/exceptions.md
      - Email Processors:
          - Base: api/processors/base.md
          - Default: api/processors/default.md
          - Celery: api/processors/celery.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: google

theme:
  name: readthedocs
  highlightjs: true

markdown_extensions:
  smarty: {}
  toc:
    permalink: true
  sane_lists: {}
