# Generated by Django 2.2 on 2024-11-25 08:49

from django.db import migrations, models
import easy_email.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, null=True, upload_to=easy_email.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('recipients', models.TextField(blank=True, null=True)),
                ('from_email', models.CharField(blank=True, max_length=100, null=True)),
                ('cc', models.TextField(blank=True, null=True)),
                ('send_time', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[[1, 'Success'], [2, 'Error']], max_length=50, null=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('attachments', models.ManyToManyField(blank=True, to='easy_email.Attachment')),
            ],
        ),
    ]
