# Generated by Django 2.2 on 2024-11-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.IntegerField(blank=True, choices=[[1, 'Success'], [2, 'Error']], null=True),
        ),
    ]
