# Generated by Django 2.2 on 2024-11-25 18:10

from django.db import migrations, models
import easy_email.validators


class Migration(migrations.Migration):

    dependencies = [
        ('easy_email', '0003_auto_20241125_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(help_text='Only underscore (_), lowercase characters, and numbers are allowed. Name cannot start with a number.', max_length=50, unique=True, validators=[easy_email.validators.TemplateNameValidator()]),
        ),
    ]
