# Generated by Django 2.2 on 2025-03-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_email', '0004_auto_20241126_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='is_sent',
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.IntegerField(blank=True, choices=[[0, 'Pending'], [1, 'Success'], [2, 'Error']], default=0, null=True),
        ),
    ]
