# Generated by Django 3.2 on 2025-03-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_email', '0006_auto_20250318_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
